### ISSUE TITLE
测试demo中打印一张小票功能异常

### ISSUE THREAD

**Issue by lintai** [shangmisunmi/SunmiPrinterDemo#20]
我的设备是D2，打印设备是普通的打印机不是K1，
现在这边的传参
MainActivity.printerPresenter.printerService.sendRAWData(getBaiduTestBytes(), null);
                        MainActivity.printerPresenter.printerService.lineWrap(3, null);
                        MainActivity.printerPresenter.printerService.cutPaper(null);

demo中ICallback的传参为null，程序异常，这边该如何处理？

**Comment by lintai** [comment]
Process: com.sunmi.rongxianda.s, PID: 4309
    java.lang.NullPointerException: Attempt to invoke interface method 'void woyou.aidlservice.jiuiv5.ICallback.onRaiseException(int, java.lang.String)' on a null object reference
        at android.os.Parcel.readException(Parcel.java:1690)
        at android.os.Parcel.readException(Parcel.java:1637)
        at com.sunmi.peripheral.printer.SunmiPrinterService$Stub$Proxy.lineWrap(SunmiPrinterService.java:792)
        at com.sunmi.sunmit2demo.fragment.DeviceFragment.onClick(DeviceFragment.java:84)
