### ISSUE TITLE
printerlibrary:1.0.15 crashes after R8

### ISSUE THREAD

**Issue by gmk57** [shangmisunmi/SunmiPrinterDemo#60]
Stack trace:
```
java.lang.NoSuchMethodError: No static method a(Ljava/lang/String;)Ljava/lang/String; in class Landroid/os/SystemProperties; or its super classes (declaration of 'android.os.SystemProperties' appears in /system/framework/framework.jar)
    at com.sunmi.peripheral.printer.SunmiPrinterService$Stub$Proxy.setTable(SunmiPrinterService.java:632)
    at com.sunmi.peripheral.printer.SunmiPrinterService$Stub$Proxy.<init>(SunmiPrinterService.java:628)
    at com.sunmi.peripheral.printer.SunmiPrinterService$Stub.asInterface(SunmiPrinterService.java:37)
    at com.sunmi.peripheral.printer.InnerPrinterCallback.onServiceConnected(InnerPrinterCallback.java:21)
```
or
```
java.lang.NoSuchFieldError: No field a of type I in class Landroid/os/SystemProperties; or its superclasses (declaration of 'android.os.SystemProperties' appears in /system/framework/framework.jar)
    at com.sunmi.peripheral.printer.SunmiPrinterService$Stub$Proxy.setTable(SunmiPrinterService.java:632)
    at com.sunmi.peripheral.printer.SunmiPrinterService$Stub$Proxy.<init>(SunmiPrinterService.java:628)
    at com.sunmi.peripheral.printer.SunmiPrinterService$Stub.asInterface(SunmiPrinterService.java:37)
    at com.sunmi.peripheral.printer.InnerPrinterCallback.onServiceConnected(InnerPrinterCallback.java:21)
```

This is caused by
```
String model = SystemProperties.get("ro.sunmi.hardware").toUpperCase(Locale.ENGLISH);
```
at line 664 of (decompiled) SunmiPrinterService.java

## Fix
Add to `proguard-rules.pro`:
`-keep class android.os.SystemProperties { get(java.lang.String); }`
Ideally this should be added to library's `consumer-rules.pro`.

**Comment by shenjingfs** [comment]
It still crashes, even if rule are added `-keep class android.os.SystemProperties {*;}`

Log
`java.lang.NoSuchFieldError: No field VERSION_CODE of type Ljava/lang/String; in class Landroid/os/SystemProperties; or its superclasses (declaration of 'android.os.SystemProperties' appears in /system/framework/framework.jar)`

## Fix:
Downgrade  to 1.0.13 solved! And there is no need to add additional proguard rules

**Comment by masmil1988** [comment]
> It still crashes, even if rule are added `-keep class android.os.SystemProperties {*;}`
> 
> Log `java.lang.NoSuchFieldError: No field VERSION_CODE of type Ljava/lang/String; in class Landroid/os/SystemProperties; or its superclasses (declaration of 'android.os.SystemProperties' appears in /system/framework/framework.jar)`
> 
> ## Fix:
> Downgrade to 1.0.13 solved! And there is no need to add additional proguard rules

Downgrading to 1.0.14 is enough to avoid the crash.
Anyway, this still remains an issue...

**Comment by rynkowsg** [comment]
I guess the bizarre idea behind adding within a library `android.os.SystemProperties` is to access the system's `android.os.SystemProperties` which are not available for an app/lib developer. 

The SystemProperties is implemented with JNI - the impl is split into two parts: C++'s `android_os_SystemProperties.cpp` (implementing the access) and Java's `android.os.SystemProperties` (providing Java interface). 

The printerlibrary provides a copy of `android.os.SystemProperties` (probably an exact copy of SystemProperties.java from Sunmi Android OS source code). Just the face of the JNI-bridged implementation, to access natively implemented part.

Sounds like quite a hack 😬

**Comment by rynkowsg** [comment]
Looking at the content of the sunmi libraries, it looks they fixed the issue in 1.0.18.

| 1.0.14                                                                                                                                               | 1.0.15                                                                                                                                               | 1.0.16                                                                                                                                               | 1.0.17                                                                                                                                               | 1.0.18                                                                                                                                               | 1.0.19                                                                                                                                               |
| ---------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------- |
| ![Screen Shot 2022-09-21 at 12 11 49 - 1 0 14](https://user-images.githubusercontent.com/5878299/191490903-2dcfe0a8-2d63-4615-b91a-c057d2c34707.png) | ![Screen Shot 2022-09-21 at 12 13 20 - 1 0 15](https://user-images.githubusercontent.com/5878299/191490954-24f5ef0a-71b8-4c68-aa08-31b4cf940173.png) | ![Screen Shot 2022-09-21 at 12 14 01 - 1 0 16](https://user-images.githubusercontent.com/5878299/191490956-5d9a864e-6a77-4410-8dde-21538ce61696.png) | ![Screen Shot 2022-09-21 at 12 09 02 - 1 0 17](https://user-images.githubusercontent.com/5878299/191490975-1f26bf60-ccb4-4ece-8144-cdd692ddf969.png) | ![Screen Shot 2022-09-21 at 12 10 03 - 1 0 18](https://user-images.githubusercontent.com/5878299/191490977-12819293-0101-4dfe-9f47-6621710bab02.png) | ![Screen Shot 2022-09-21 at 12 10 51 - 1 0 19](https://user-images.githubusercontent.com/5878299/191490978-792cf7bc-23d6-43c1-8882-de896effc67d.png) |
